# Generated by Django 5.2.8 on 2025-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDPrintingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='3d-printing/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('material', models.CharField(blank=True, help_text='e.g., PLA, ABS, PETG', max_length=100)),
                ('print_time', models.CharField(blank=True, help_text='Estimated print time', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3D Printing Project',
                'verbose_name_plural': '3D Printing Projects',
                'ordering': ['order', 'title_en'],
            },
        ),
    ]
